#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : user-agents
Version  : 1.1.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/be/ff/886a1e2570784ee63b1c4b0fd77037b84087ffe7b7b45f9751285418be34/user-agents-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/be/ff/886a1e2570784ee63b1c4b0fd77037b84087ffe7b7b45f9751285418be34/user-agents-1.1.0.tar.gz
Summary  : A library to identify devices (phones, tablets) and their capabilities by parsing (browser/HTTP) user agent strings
Group    : Development/Tools
License  : MIT
Requires: user-agents-python3
Requires: user-agents-license
Requires: user-agents-python
Requires: ua-parser
BuildRequires : buildreq-distutils3
BuildRequires : ua-parser

%description
==================
        
        ``user_agents`` is a Python library that provides an easy way to
        identify/detect devices like mobile phones, tablets and their
        capabilities by parsing (browser/HTTP) user agent strings. The goal is

%package license
Summary: license components for the user-agents package.
Group: Default

%description license
license components for the user-agents package.


%package python
Summary: python components for the user-agents package.
Group: Default
Requires: user-agents-python3

%description python
python components for the user-agents package.


%package python3
Summary: python3 components for the user-agents package.
Group: Default
Requires: python3-core

%description python3
python3 components for the user-agents package.


%prep
%setup -q -n user-agents-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534859518
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/user-agents
cp LICENSE.txt %{buildroot}/usr/share/doc/user-agents/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/user-agents/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
