#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : user-agents
Version  : 2.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/ef/b4/3ae0f6baeddc7264a3de3ebca9fe381d09ebed4ac14fb8510ac4b3d70197/user-agents-2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ef/b4/3ae0f6baeddc7264a3de3ebca9fe381d09ebed4ac14fb8510ac4b3d70197/user-agents-2.0.tar.gz
Summary  : A library to identify devices (phones, tablets) and their capabilities by parsing (browser/HTTP) user agent strings
Group    : Development/Tools
License  : MIT
Requires: user-agents-license = %{version}-%{release}
Requires: user-agents-python = %{version}-%{release}
Requires: user-agents-python3 = %{version}-%{release}
Requires: ua-parser
BuildRequires : buildreq-distutils3
BuildRequires : ua-parser

%description
Python User Agents
==================
``user_agents`` is a Python library that provides an easy way to
identify/detect devices like mobile phones, tablets and their
capabilities by parsing (browser/HTTP) user agent strings. The goal is
to reliably detect whether:

%package license
Summary: license components for the user-agents package.
Group: Default

%description license
license components for the user-agents package.


%package python
Summary: python components for the user-agents package.
Group: Default
Requires: user-agents-python3 = %{version}-%{release}

%description python
python components for the user-agents package.


%package python3
Summary: python3 components for the user-agents package.
Group: Default
Requires: python3-core

%description python3
python3 components for the user-agents package.


%prep
%setup -q -n user-agents-2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554650936
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/user-agents
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/user-agents/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/user-agents/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
